name: Build and deploy Node.js backend to Azure Web App - express-backend-1006

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    defaults:
      run:
        working-directory: backend  # 👈🏽 Target backend folder

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm install

      - name: Zip backend files
        run: zip -r ../backend-release.zip ./*

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend-artifact
          path: backend-release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: backend-artifact

      - name: Unzip artifact
        run: unzip backend-release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_8285AC68CB56489DB9327B85FAA698E8 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_B91A0A3AB7354AA8A2C573FBBAE0873E }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_F3C356773B1F411FBB371A7B16EC43FA }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'express-backend-1006'
          slot-name: 'Production'
          package: .
